services:
  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - '9098:8080'
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
