services:
  keycloak-service:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - '9098:8080'
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - /opt/keycloak/data

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_db
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

  Reclamation_Service:
    container_name: reclamation_service
    image: dark9040/reclamation_service
    build: ./reclamation_service
    ports:
      - "8083:8083"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    depends_on:
      - Eureka

  Eureka:
    container_name: eureka
    build: ./EurekaApplication
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: dark9040/eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

  api-gateway:
    build: ./api-gateway
    image: dark9040/apigateway
    ports:
      - "8093:8093"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - Eureka
      - Reclamation_Service
      




volumes:
  mysql-data:
