services:
  Eureka:
     container_name: eureka
     build: .\EurekaApplication
     hostname: serviceregistry
     ports:
       - "8761:8761"
     image: dark9040/eureka
     environment:
       - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
  api-gateway:
     build: .\api-gateway
     image: dark9040/apigateway
     ports:
       - "8093:8093"  # Port mapping pour l'API Gateway
     environment:
       - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
     depends_on:
       - "Eureka"
       - "Reclamation_Service"

  Reclamation_Service:
     container_name: reclamation_service
     image: dark9040/reclamation_service
     build: ./reclamation_service
     ports:
       - '8083:8083'
     environment:
       - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
     depends_on:
       - Eureka

    # order-service:
      # build: ./ordre-service
      # image: gofraneab/mini-project-microservice-order:latest
      # container_name: ordercontainer
      # ports:
        # - '8082:8082'
      # depends_on:
        # - Eureka
      # environment:
        # - spring.datasource.username=gofrane
        # - spring.datasource.password=
        # - spring.datasource.url=jdbc:h2:file:./Database/Data/orderDB
        # - spring.datasource.driver-class-name=org.h2.Driver
        # - spring.jpa.hibernate.ddl-auto=update
        # - eureka.client.service-url.defaultZone=http://eureka:8761/eureka

  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:23.0.0
    ports:
      - '9098:8080'
    command:
      - start-dev
      # you can also pass flags here, for example:
      # - --http-port=8080
      # - --hostname-strict=false
    environment:
      # as of Keycloak 17+ these are the correct variables:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
